# -*- mode: yaml -*-
# Config file for ReBench

runs:
    max_invocation_time: 360

benchmark_suites:
    macro:
        gauge_adapter: RebenchLog
        command: "-c core-lib/Smalltalk core-lib/Examples/Benchmarks core-lib/Examples/Benchmarks/Richards core-lib/Examples/Benchmarks/DeltaBlue core-lib/Examples/Benchmarks/NBody core-lib/Examples/Benchmarks/Json core-lib/Examples/Benchmarks/GraphSearch -- BenchmarkHarness %(benchmark)s %(iterations)s "
        benchmarks:
            - Richards:     {extra_args: 1}
            - DeltaBlue:    {extra_args: 500}
            - NBody:        {extra_args: 7000}
            - JsonSmall:    {extra_args: 15}
            - GraphSearch:  {extra_args: 12}
            - PageRank:     {extra_args: 150}

    micro:
        gauge_adapter: RebenchLog
        command: "-c core-lib/Smalltalk core-lib/Examples/Benchmarks core-lib/Examples/Benchmarks/LanguageFeatures -- BenchmarkHarness %(benchmark)s %(iterations)s "
        benchmarks:
            - Fannkuch:     {extra_args: 7}
            - Fibonacci:    {extra_args: "20"}
            - Dispatch:     {extra_args: 30}
            - Bounce:       {extra_args: "30"}
            - Loop:         {extra_args: 30}
            - Permute:      {extra_args: "30"}
            - Queens:       {extra_args: "25"}
            - List:         {extra_args: "20"}
            - Recurse:      {extra_args: "30"}
            - Storage:      {extra_args: 20}
            - Sieve:        {extra_args: 30}
            - BubbleSort:   {extra_args: "30"}
            - QuickSort:    {extra_args: 40}
            - Sum:          {extra_args: 10}
            - Towers:       {extra_args: "20"}
            - TreeSort:     {extra_args: "20"}
            - IntegerLoop:  {extra_args: 10}
            - FieldLoop:    {extra_args: 10}
            - WhileLoop:    {extra_args: 60}
            - Mandelbrot:   {extra_args: 100}

experiments:
    elision:
        suites:
            - micro
            - macro
        executions:
            - &FINALISATION_OPT finalisation_opt
            - &FINALISATION_NAIVE finalisation_naive
    perf:
        suites:
            - micro
            - macro
        executions:
            - &PERF_RC perf_rc
            - &PERF_GC perf_gc
    barriers:
        suites:
            - micro
            - macro
        executions:
            - &BARRIERS_NAIVE barriers_naive
            - &BARRIERS_NONE barriers_none
            - &BARRIERS_OPT barriers_opt

.common:
    paths:
        - &SOM_RS_FE_PATH "../raw_data/som_rs_finaliser_elision/finaliser_count.data"
        - &SOM_RS_BARRIERS_PATH "../raw_data/som_rs_barriers/finaliser_count.data"

executors:
    *PERF_RC:
        env:
            GC_DONT_GC: "true"
        path: som-rs
        executable: ./perf_rc/release/som-interpreter-bc
    *PERF_GC:
        path: som-rs
        executable: ./perf_gc/release/som-interpreter-bc
    *FINALISATION_OPT:
        env:
            FINALIZER_COUNT_PATH: *SOM_RS_FE_PATH
            CFG_NAME: *FINALISATION_OPT
        path: som-rs
        executable: ./finalisation_opt/release/som-interpreter-bc
    *FINALISATION_NAIVE:
        env:
            FINALIZER_COUNT_PATH: *SOM_RS_FE_PATH
            CFG_NAME: *FINALISATION_NAIVE
        path: som-rs
        executable: ./finalisation_naive/release/som-interpreter-bc
    *BARRIERS_NAIVE:
        env:
            FINALIZER_COUNT_PATH: *SOM_RS_BARRIERS_PATH
            CFG_NAME: *BARRIERS_NAIVE
        path: som-rs
        executable: ./barriers_naive/release/som-interpreter-bc
    *BARRIERS_NONE:
        env:
            FINALIZER_COUNT_PATH: *SOM_RS_BARRIERS_PATH
            CFG_NAME: *BARRIERS_NONE
        path: som-rs
        executable: ./barriers_none/release/som-interpreter-bc
    *BARRIERS_OPT:
        env:
            FINALIZER_COUNT_PATH: *SOM_RS_BARRIERS_PATH
            CFG_NAME: *BARRIERS_OPT
        path: som-rs
        executable: ./barriers_opt/release/som-interpreter-bc

