# -*- mode: yaml -*-
# Config file for ReBench

runs:
    max_invocation_time: 360

benchmark_suites:
    macro:
        gauge_adapter: RebenchLog
        command: &MACRO_CMD "--cp SOM/Smalltalk:SOM/Examples/Benchmarks/Richards:SOM/Examples/Benchmarks/DeltaBlue:SOM/Examples/Benchmarks/NBody:SOM/Examples/Benchmarks/Json:SOM/Examples/Benchmarks/GraphSearch SOM/Examples/Benchmarks/BenchmarkHarness.som %(benchmark)s %(iterations)s"
        benchmarks:
            - Richards:     {extra_args: 1}
            - DeltaBlue:    {extra_args: 500}
            - NBody:        {extra_args: 7000}
            - JsonSmall:    {extra_args: 15}
            - GraphSearch:  {extra_args: 12}
            - PageRank:     {extra_args: 150}

    micro:
        gauge_adapter: RebenchLog
        command: "--cp SOM/Smalltalk:SOM/Examples/Benchmarks/LanguageFeatures SOM/Examples/Benchmarks/BenchmarkHarness.som %(benchmark)s %(iterations)s"
        benchmarks:
            - Fannkuch:     {extra_args: 7}
            - Fibonacci:    {extra_args: "20"}
            - Dispatch:     {extra_args: 30}
            - Bounce:       {extra_args: "30"}
            - Loop:         {extra_args: 30}
            - Permute:      {extra_args: "30"}
            - Queens:       {extra_args: "25"}
            - List:         {extra_args: "20"}
            - Recurse:      {extra_args: "30"}
            - Storage:      {extra_args: 20}
            - Sieve:        {extra_args: 30}
            - BubbleSort:   {extra_args: "30"}
            - QuickSort:    {extra_args: 40}
            - Sum:          {extra_args: 10}
            - Towers:       {extra_args: "20"}
            - TreeSort:     {extra_args: "20"}
            - IntegerLoop:  {extra_args: 10}
            - FieldLoop:    {extra_args: 10}
            - WhileLoop:    {extra_args: 60}
            - Mandelbrot:   {extra_args: 100}

experiments:
    finaliser_elision:
        suites:
            - micro
            - macro
        executions:
            - &FINALISATION_OPT finalisation_opt
            - &FINALISATION_NAIVE finalisation_naive
    barriers:
        suites:
            - micro
            - macro
        executions:
            - &BARRIERS_NAIVE barriers_naive
            - &BARRIERS_NONE barriers_none
            - &BARRIERS_OPT barriers_opt

.common:
    paths:
        - &SOM_RS_FE_PATH "../raw_data/yksom_finaliser_elision/finaliser_count.data"
        - &SOM_RS_BARRIERS_PATH "../raw_data/yksom_barriers/finaliser_count.data"

executors:
    *FINALISATION_OPT:
        # env:
        #     FINALIZER_COUNT_PATH: *SOM_RS_FE_PATH
        #     CFG_NAME: *FINALISATION_OPT
        path: yksom
        executable: ./finalisation_opt/release/yksom
    *FINALISATION_NAIVE:
        # env:
        #     FINALIZER_COUNT_PATH: *SOM_RS_FE_PATH
        #     CFG_NAME: *FINALISATION_NAIVE
        path: yksom
        executable: ./finalisation_naive/release/yksom
    *BARRIERS_NAIVE:
        # env:
        #     FINALIZER_COUNT_PATH: *SOM_RS_BARRIERS_PATH
        #     CFG_NAME: *BARRIERS_NAIVE
        path: yksom
        executable: ./barriers_naive/release/yksom
    *BARRIERS_NONE:
        # env:
        #     FINALIZER_COUNT_PATH: *SOM_RS_BARRIERS_PATH
        #     CFG_NAME: *BARRIERS_NONE
        path: yksom
        executable: ./barriers_none/release/yksom
    *BARRIERS_OPT:
        # env:
        #     FINALIZER_COUNT_PATH: *SOM_RS_BARRIERS_PATH
        #     CFG_NAME: *BARRIERS_OPT
        path: yksom
        executable: ./barriers_opt/release/yksom

